[tool.poetry]
name = "sparse_autoencoder"
version = "0.0.0"  
description = "Sparse Autoencoder for Mechanistic Interpretability"
authors = ["Alan Cooney <41682961+alan-cooney@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
include = ["sparse_autoencoder"]

[tool.poetry.dependencies]
python = ">=3.10, <3.13"
einops = ">=0.6"
torch = ">=2.1"
zstandard = "^0.21.0"
wandb = "^0.15.12"

[tool.poetry.group.dev.dependencies]
pytest = ">=7"
pytest-cov = ">=4"
jupyter = ">=1"
plotly = ">=5"
pylint = "^3.0.2"
ruff = "^0.1.4"
pyright = "^1.1.334"

[tool.poetry.group.demos.dependencies]
jupyterlab = ">=3"
transformer-lens = "^1.9.0"
pandas = ">=2.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:pkg_resources is deprecated as an API:DeprecationWarning",
    # Ignore numpy.distutils deprecation warning caused by pandas
    # More info: https://numpy.org/doc/stable/reference/distutils.html#module-numpy.distutils
    "ignore:distutils Version classes are deprecated:DeprecationWarning"
]
addopts = """--jaxtyping-packages=sparse_autoencoder,beartype.beartype \ 
-W ignore::beartype.roar.BeartypeDecorHintPep585DeprecationWarning \ 
--doctest-modules"""


[tool.ruff]
exclude = [
    "/.venv",
    "*/snapshots/",
]
select = ["E", "F", "I001"] # errors, flake8, isort equivalents
ignore = ["E402", "E721", "E731", "E741", "F722"]
ignore-init-module-imports = true
fixable = ["I001", "F401"] # Auto-fix isort, unused variables
line-length = 100

[tool.ruff.isort]
combine-as-imports = true # Combine imports from the same module
lines-after-imports = 2

[tool.pyright]
reportIncompatibleMethodOverride = true
include = ["sparse_autoencoder"]